#!/usr/bin/bash
#
# joke program 'pseudovirus'
# Give this script execution rights to the DE application launcher.
# Specify the application launcher of the firefox icon to launch this script.
# to launch this script, it will launch firefox after displaying a joke message.
# It's a malicious joke, but it does no real harm. If you show the script, you will be convinced.
# - You need to install zenity.
# pacman -S zenity
# -Give them execution rights.
# chmod +x pseudovirus
# Translated with DeepL.com (free version)
 

# JOKE MESSAGE
    sleep 1
    zenity --info --text="Virus detected.\nThe system had fatal damage.\nReinstall OS"
    zenity --info --text="It is lie."

#   
# LAUNCH APPLIUCATION
#
/usr/lib/firefox/firefox
